Updating linux_run script for XDr installs to account for older RHEL versions
hmcts/terraform-module-vm-bootstrap pull request #71
Opened 2024-09-10 11:13 UTC by MartyFox

### Change description
Updating linux_run script for XDr installs to account for older RHEL versions

2024-09-10 11:29 UTC, JordanHoey96 approved these changes

2024-09-10 12:00 UTC, cpareek requested changes
Do we know if the XDR Agent install supported on RedHat 6?

2024-09-10 16:06 UTC, MartyFox commented
> Do we know if the XDR Agent install supported on RedHat 6?

Should be supported on RHEL6.10+: https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR/Cortex-XDR-Compatibility-Matrix/Linux

I've updated this script to include install and download commands for RHEL6 specifically

2024-09-11 09:16 UTC, cpareek commented
> > Do we know if the XDR Agent install supported on RedHat 6?
> 
> Should be supported on RHEL6.10+: https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR/Cortex-XDR-Compatibility-Matrix/Linux
> 
> I've updated this script to include install and download commands for RHEL6 specifically

sure - think best to test this branch on the RHEL 6 and 7 before merging to the master

2024-09-12 08:28 UTC, closed without merging